version: '3'

volumes:
  ez-production-data:

services:
  backend:
    image: ghcr.io/envelope-zero/backend:v3.4.1
    volumes:
      - ez-production-data:/data
    environment:
      API_URL: http://localhost:3001/api
      CORS_ALLOW_ORIGINS: http://localhost:3001

  frontend:
    image: ez-frontend
    build:
      context: .
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'

  proxy:
    image: nginx:1.25.3-alpine
    volumes:
      - $PWD/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '3001:80'
