name: Cypress

on:
  push:

jobs:
  cypress:
    runs-on: ubuntu-latest

    # Current backend version as service container
    services:
      backend:
        image: ghcr.io/envelope-zero/backend:v0.36.1
        env:
          CORS_ALLOW_ORIGINS: http://localhost:3000
          API_URL: http://localhost:8080
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v3.0.2

      - uses: cypress-io/github-action@v4.2.0
        env:
          REACT_APP_API_ENDPOINT: http://localhost:8080/v1
        with:
          start: npm start
          # Frontend runs on :3000, API on :8080
          wait-on: 'http://localhost:3000, http://localhost:8080'

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
